### ISSUE TITLE
keeps rebooting

### ISSUE THREAD

**Issue by BuckfastBeekeeper** [JoepSchyns/Low_power_TTGO_T-beam#1]
rst:0x1 (POWERON_RESET),boot:0x37 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0018,len:4
load:0x3fff001c,len:808
load:0x40078000,len:6084
load:0x40080000,len:6696
entry 0x400802e4
GPIO pins disabled: 1
TurnOff: bluedroid
Disable: ESP_ERR_INVALID_STATE
Dinit: ESP_ERR_INVALID_STATE
Guru Meditation Error: Core  1 panic'ed (LoadProhibited). Exception was unhandled.
Core 1 register dump:
PC      : 0x400f8636  PS      : 0x00060530  A0      : 0x800d11ce  A1      : 0x3ffb1ec0  
A2      : 0x00000000  A3      : 0x3f401450  A4      : 0x3ffc5a88  A5      : 0x0000ff00  
A6      : 0x00ff0000  A7      : 0xff000000  A8      : 0x800d1f86  A9      : 0x3ffb1ef0  
A10     : 0x00000010  A11     : 0x3f401458  A12     : 0x000000ff  A13     : 0x0000ff00  
A14     : 0x00ff0000  A15     : 0xff000000  SAR     : 0x00000010  EXCCAUSE: 0x0000001c  
EXCVADDR: 0x00000150  LBEG    : 0x400013f9  LEND    : 0x4000140d  LCOUNT  : 0xfffffffe  

Backtrace: 0x400f8636:0x3ffb1ec0 0x400d11cb:0x3ffb1f00 0x400d13ef:0x3ffb1f40 0x40111933:0x3ffb1fa0

Rebooting...
ets Jun  8 2016 00:22:57

rst:0xc (SW_CPU_RESET),boot:0x37 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0018,len:4
load:0x3fff001c,len:808
load:0x40078000,len:6084
load:0x40080000,len:6696
entry 0x400802e4
GPIO pins disabled: 1
TurnOff: bluedroid
Disable: ESP_ERR_INVALID_STATE
Dinit: ESP_ERR_INVALID_STATE
Guru Meditation Error: Core  1 panic'ed (LoadProhibited). Exception was unhandled.
Core 1 register dump:
PC      : 0x400f8636  PS      : 0x00060530  A0      : 0x800d11ce  A1      : 0x3ffb1ec0  
A2      : 0x00000000  A3      : 0x3f401450  A4      : 0x3ffc5a88  A5      : 0x0000ff00  
A6      : 0x00ff0000  A7      : 0xff000000  A8      : 0x800d1f86  A9      : 0x3ffb1ef0  
A10     : 0x00000010  A11     : 0x3f401458  A12     : 0x000000ff  A13     : 0x0000ff00  
A14     : 0x00ff0000  A15     : 0xff000000  SAR     : 0x00000010  EXCCAUSE: 0x0000001c  
EXCVADDR: 0x00000150  LBEG    : 0x400013f9  LEND    : 0x4000140d  LCOUNT  : 0xfffffffe  

Backtrace: 0x400f8636:0x3ffb1ec0 0x400d11cb:0x3ffb1f00 0x400d13ef:0x3ffb1f40 0x40111933:0x3ffb1fa0

Rebooting...
ets Jun  8 2016 00:22:57

rst:0xc (SW_CPU_RESET),boot:0x37 (SPI_FAST_FLASH_BOOT)
configsip: 0, SPIWP:0xee
clk_drv:0x00,q_drv:0x00,d_drv:0x00,cs0_drv:0x00,hd_drv:0x00,wp_drv:0x00
mode:DIO, clock div:1
load:0x3fff0018,len:4
load:0x3fff001c,len:808
load:0x40078000,len:6084
load:0x40080000,len:6696
entry 0x400802e4
GPIO pins disabled: 1
TurnOff: bluedroid
Disable: ESP_ERR_INVALID_STATE
Dinit: ESP_ERR_INVALID_STATE
Guru Meditation Error: Core  1 panic'ed (LoadProhibited). Exception was unhandled.
Core 1 register dump:
PC      : 0x400f8636  PS      : 0x00060530  A0      : 0x800d11ce  A1      : 0x3ffb1ec0  
A2      : 0x00000000  A3      : 0x3f401450  A4      : 0x3ffc5a88  A5      : 0x0000ff00  
A6      : 0x00ff0000  A7      : 0xff000000  A8      : 0x800d1f86  A9      : 0x3ffb1ef0  
A10     : 0x00000010  A11     : 0x3f401458  A12     : 0x000000ff  A13     : 0x0000ff00  
A14     : 0x00ff0000  A15     : 0xff000000  SAR     : 0x00000010  EXCCAUSE: 0x0000001c  
EXCVADDR: 0x00000150  LBEG    : 0x400013f9  LEND    : 0x4000140d  LCOUNT  : 0xfffffffe  

Backtrace: 0x400f8636:0x3ffb1ec0 0x400d11cb:0x3ffb1f00 0x400d13ef:0x3ffb1f40 0x40111933:0x3ffb1fa0

Rebooting...
ets Jun  8 2016 00:22:57

**Comment by JoepSchyns** [comment]
Interesting. I have not seen such run time errors on my t-beam before. I'm curious what _"Guru Meditation Error: Core 1 panic'ed (LoadProhibited). Exception was unhandled."_ exactly means. It seems to me that your t-beam cannot go into deep sleep. But that is me guessing.

**Comment by DeuxVis** [comment]
Might be interesting to compare your TBeam revisions. As usual with TTGO they sold different versions with some minor changes in the schematic and different GPS modules - some with Neo 6M and others Neo M8N.

**Comment by BuckfastBeekeeper** [comment]
Neo 6M-0-001
There is a Nr T22_V07   next  20180711 Is this a production date?
I also have a DHT11 and a display connected.

**Comment by DeuxVis** [comment]
> There is a Nr T22_V07 next 20180711 Is this a production date?

Probably not _production date_, but rather _release of this version date_, and the T22_V07 is revision number.

**Comment by JoepSchyns** [comment]
@BuckfastBeekeeper We have got the same versions of the Neo and the same T-beam revision. I do not have anything connected at the moment so that could be a contributor to your problem. But I'am not sure.

**Comment by BuckfastBeekeeper** [comment]
I disconnected all the breadboard wires.
It is completely stand alone now, but still it keeps rebooting.

So i don't understand the diff.

**Comment by JoepSchyns** [comment]
Hmm have you tried the example EPS32->DeepSleep->TimerWakeUp sketch provided with the esp32 Arduino core? I'am curious whether deep sleep works for you without any added complications.

**Comment by BuckfastBeekeeper** [comment]
https://github.com/espressif/arduino-esp32/tree/master/libraries/ESP32/examples/DeepSleep

i have implemented this "Timer wake up" part in a GPS logger sketch and combined them with GPS,temp and Humid data too Lora TTN.

The TTGO-BEAM goes to sleep, but it still takes 10-20 Ma.
That why i am interested in maybe switching of more to lower the power consumption.

**Comment by eumaios** [comment]
Thank you @JoepSchyns for this work - I was looking for this a while! It would be really nice to combine this code with the @DeuxVis code here https://github.com/DeuxVis/Lora-TTNMapper-T-Beam - in fact to reduce power consumption is on their To do list at the bottom 

Initially, I had the exact same rebooting error like @BuckfastBeekeeper . I found that I could make it work by installing the Expressif / Arduino Esp32 board according to this procedure: https://github.com/espressif/arduino-esp32/blob/master/docs/arduino-ide/mac.md

In the newly installed boards, I chose the "TBeam" board.
