### ISSUE TITLE
unclear on GPS pins

### ISSUE THREAD

**Issue by EtoTen** [JoepSchyns/Low_power_TTGO_T-beam#3]
Hi, I am confused by your readme file. Are you saying that you have to solder the extra GPS module pins in order to put the GPS module to sleep? Or can they be left as is?

"During testing is established that the Neo-6m does execute UBX commands in NMEA mode, but does not send back an acknowledgement. Therefore ubox commands cannot be verified. Nonetheless pins 14 and 15 are exposed on the t-beam, thus they could be soldered by hand to two GPIO pins thereby enabling switching of protocols."

**Comment by JoepSchyns** [comment]
Hi, I updated the readme. Hopefully it is clear now.

_"Neo does execute UBX commands in NMEA mode but does not send back acknowledgements. Therefore UBX commands, such as the sleep command, that do not require acknowledgements work out of the box."_
