### ISSUE TITLE
Missing sketch to achieve 10ma on T-Beam

### ISSUE THREAD

**Issue by MrSniffer** [JoepSchyns/Low_power_TTGO_T-beam#6]
In read.md it is stated that "This sketch demonstrates how battery consumption can be reduced to 10ma during sleep, see image below. Please feel free to push more power reduction methods."

The link is broken. Can you please repost the sketch? I have tried to power down the GPS using the PMU but the GPS continue to search for satellites, blink the red LED, etc. Your sketch would be very helpful.

**Comment by JoepSchyns** [comment]
Github removed the image. The sketch is in the repo itself. Good luck! I was not able to get power consumption low enough for my goals.
